### ISSUE TITLE
Edit modal for selected assignment

### ISSUE THREAD

**Issue by harryt04** [Jcroxford/grader-aide#19]
Steps to reproduce: 

1. select an assignment
2. click edit modal, (optional: make changes)
3. switch to another assignment
4. click edit modal

5. **Loads rules and comments of first assignment in modal**

**Comment by Jcroxford** [comment]
alright. This bug still exists in milestone 1. But it is fixed in milestone 2 and that is where our efforts are focused. Closing this issue
